### ISSUE TITLE
Helper Display to shows notes and main slides 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mpflanzer/splitshow#18]
```
It would be great, if the the Helper Display could show the whole pdf and the 
Main Display will only show the right half or an adjustable amount.


```

Original issue reported on code.google.com by `ichbinbe...@gmail.com` on 16 Apr 2012 at 6:30

**Comment by mpflanzer** [comment]
Can be done by using the preview window in full screen mode (Ctrl + Cmd + f) and one presentation display.
