### ISSUE TITLE
The timer is automatically reseting after exit from fullscreen

### ISSUE THREAD

**Issue by curiale** [mpflanzer/splitshow#30]
Hi mpflanzer,

I was thinking to change  the functionality of the timer to remember the time after exiting from fullscreen.

How to reproduce this issue:

1) Open a pdf and go to fullscreen.
2) Start the timer and wait for few seconds.
3) Exit from fullscreen.
4) Go back to fullscreen -> The timer is automatically reset to 0

I prefer that the timer remembers the previous state and if I want reset the timer manually.
Are you ok with this functionality ? If you are ok with this functionality I can modify this behavior in the code.

**Comment by mpflanzer** [comment]
Yes, I agree that it should not be reset when leaving fullscreen mode. Would be great if you could change the behaviour.
