### ISSUE TITLE
Note page is in a wrong place

### ISSUE THREAD

**Issue by sk-attack** [mpflanzer/splitshow#32]
Thank you very much for your development of SplitShow, which is my favorite.

I compiled and built the newest programs of SplitShow and got the application of new one (SplitShow ver 0.9.5) without any trouble. Also I can opened and see my slide by the new SplitShow. 
However, the note displayed  in the screen is in wrong place.  Let's explain what happened to my mac comparing in "original SplitShow (ver 0.9.1)"  and "new SplitShow (ver. 0.9.5)".

The original SplitShow (ver 0.9.1)"  can display the slide correctly as shown in Figures 1, 2: 
![3](https://cloud.githubusercontent.com/assets/13460181/8842794/cbbb7d68-3139-11e5-87f3-5dd597809fae.jpg)
(Fig 1: The note of pages 5-7 is displayed next to the page 5)
![4](https://cloud.githubusercontent.com/assets/13460181/8842798/d1d038f6-3139-11e5-80e9-3cd806c1889c.jpg)
(Fig 2: The note of pages 5-7 is also displayed next to the page 6. 
There is no trouble.)

On the other hand, "new SplitShow (ver. 0.9.5)" displays the same slide as shown in Figures 3, 4:
![1](https://cloud.githubusercontent.com/assets/13460181/8842800/df83488a-3139-11e5-97d5-773ff861cb33.jpg)
(Fig. 3: The note is not displayed next to the page 5, why?  Instead of it, the page 6 is displayed!)
![2](https://cloud.githubusercontent.com/assets/13460181/8842802/e4e3c836-3139-11e5-8824-b08e25eca777.jpg)
(Fig. 4: After the page 7, the note of pages 5-7  is  displayed. 
It can not be used in the presentation!)

Could someone please solve such a bug?

**Comment by mpflanzer** [comment]
Would it be possible for you to send me the PDF file? Then I will have a look what is going wrong.
My email address is moritz@pflanzer.eu

**Comment by mpflanzer** [comment]
Ah, and of course the .nav file if it is not included in the PDF.

**Comment by sk-attack** [comment]
Thank you for your cooperation. I sent both .pdf and .nav files of my slide to the e-mail above. I don’t mean to rush you at all, but I really hope it will be debugged.

**Comment by mpflanzer** [comment]
Thanks for the files. I will have a look today.

**Comment by mpflanzer** [comment]
Unfortunately this cannot be fixed easily. Latex Beamer produces the same nav file for different situations where either the note pages are completely interleaved with the content pages or one note page follows a range of content pages but has to display for the complete range. There is now way of automatically detecting which is the correct interpretation.

Do you have any problem with using the the old version of SplitShow for the moment? If will think about an elegant way to solve this problem. And if you have no other problems with the old version I will not provide a quick workaround only to make this working as it would break other presentations.

**Comment by sk-attack** [comment]
Thank you very much for your advice. I will use the old version of SplitShow for a while, and wait the next improved version.

**Comment by mpflanzer** [comment]
@sk-attack With the new version you can define custom layouts in cases were the automatic guess is incorrect. This should solve this problem. Can you please try?

**Comment by mpflanzer** [comment]
Custom layouts can now be used to create arbitrary slides orderings for presentations.
