### ISSUE TITLE
Animated items (next one) shown on helper before notes slides

### ISSUE THREAD

**Issue by danielberlin** [mpflanzer/splitshow#33]
This seems to me to be very related to #32.

I have one slide with animated elements and notes. The notes should show up on the helper screen and stay there while switching to the next slide should show the next animated element on the main screen. However, on the helper screen, the next animation is shown instead of the notes. They are not displayed at all, then immediately the next slide follows.

```latex
\begin{frame}{Title}

\begin{block}{First}<1->
 \end{block}{}
\begin{block}{Second}<2->
 \end{block}

\end{frame}

\note[itemize]{
\item ...Notes...
}
```

**Comment by danielberlin** [comment]
In SplitShow 0.9.1 (2008 code.google.com), everything is working fine.

**Comment by mpflanzer** [comment]
Therefore other situations do not work in 0.9.1. ;-)
There seems to be no way to detect all slide layouts automatically because in some cases the navigation file is identical for different layouts.
I am working on a solution which will allow to customise the layout manually.

**Comment by mpflanzer** [comment]
You can now define custom layouts and assign specific slides to each display.
