### ISSUE TITLE
Remember GUI parameters after restarting like in 0.9.1

### ISSUE THREAD

**Issue by danielberlin** [mpflanzer/splitshow#34]
Hi,

I highly appreciate that dev on SplitShow is continued. I'm using it over years in version 0.9.1 and it served very well. :-)

In 0.9.6, I immediately missed the behaviour that once closed, it opens again with the same file loaded previously. Especially since it doesn't auto-reload (see #25) a changed pdf when recompiling LaTeX, it has been very useful to just close SplitShow and then re-open it.

Also I noticed that:
 * Window size is reset after restart. In 0.9.1, it remembered the size (I resize it to maximal screen width at ratio-specific optimal height).
 * "Open recent" dialog is always empty.
 * Dragging a PDF onto the dock icon which is also very useful worked in 0.9.1, but not anymore in 0.9.6.

**Comment by mpflanzer** [comment]
Good points. Should not be too hard to add these features. I will have a look when I have some spare time.

**Comment by mpflanzer** [comment]
The "Open recent" dialog should be working with the changes in 0a0b6304c2dc376431bea6c848fa58e8fc06332a and dec25b6f605de669b7df75bf0257fae3ef4d6ceb respectively. I have not created a new release yet but I will do after I looked into the other things.

**Comment by mpflanzer** [comment]
"Open recent" and dropping PDFs on the item should work now.

I will have a look at the window size and the other ideas later.

**Comment by mpflanzer** [comment]
Should all work now in version 0.9.8.
