### ISSUE TITLE
Feature Request: Main and helper monitor optional as separate windows

### ISSUE THREAD

**Issue by danielberlin** [mpflanzer/splitshow#35]
If I don't connect an external monitor, but have to give a presentation (via GoToMeeting or Skype), it would be very useful to have an option which enables to display both screens. Since in those videoconferencing apps a single window can be selected for presentation/screen sharing, I would share the main screen for the audience and have the helper screen with my notes private.

The separate windows could then also easily be moved to a separate space (https://support.apple.com/kb/PH18757).

Would highly appreciate this feature.

**Comment by mpflanzer** [comment]
Should work now with version 0.9.8. For custom layouts the "New window" display option opens a non-fullscreen window.
