### ISSUE TITLE
b575f42a seems to have broken split view

### ISSUE THREAD

**Issue by congma** [mpflanzer/splitshow#45]
The recent commit b575f42a seems to have broken split view.  Now the split mode shows the notes on both displays.

**Comment by mpflanzer** [comment]
Oh, ok. I might must have overlooked this during testing. :/
I will take a look in the evening.
Thanks for reporting this.

**Comment by mpflanzer** [comment]
Should be fixed by afe13ad

**Comment by congma** [comment]
Works for me.  Thanks!
