### ISSUE TITLE
Slides without notes are not shown in the helper display

### ISSUE THREAD

**Issue by bladerun16** [mpflanzer/splitshow#48]
I just tested SplitShow 0.9.8 (3) with the demo file, on my MacBookAir with a projector, and also on my iMac27in, with an external Apple display.
Unfortunately, when the main display shows a slide without a note, the helper display, instead of mirroring it, shows next note. The attached image shows that the note of slide 3 is shown together with slide 2. Can anybody help with this? Am I the only one to experiment this behavior? 
I am running El Capitan 

Thanks
Claudio
![splitshowmainwindow](https://cloud.githubusercontent.com/assets/11832392/20529346/1c2cd550-b0d0-11e6-9c87-4a9c5782399b.png)

**Comment by mpflanzer** [comment]
Can't reproduce it anymore. Please reopen the issue if this is still a problem for you with the latest version of SplitShow: https://github.com/mpflanzer/splitshow/releases/tag/v0.9.9-alpha
