### ISSUE TITLE
Display detection seems broken in version 0.9.8(4) on MacOS 10.11.6

### ISSUE THREAD

**Issue by domhardt** [mpflanzer/splitshow#54]
I had a version 0.9.5(15) compiled in Dec. 2015 that is working fine MacOS 10.11.6 except of the white flash at the begin of every new slide. Today I compiled version 0.9.8(4) and now in the display selection drop down menu the expected entries are missing. Please see attached screenshots!

![bildschirmfoto 2017-02-15 um 10 09 32](https://cloud.githubusercontent.com/assets/1955290/22967686/cf1668f0-f367-11e6-8bfc-86cf83b898d4.png)
![bildschirmfoto 2017-02-15 um 10 10 21](https://cloud.githubusercontent.com/assets/1955290/22967687/cf3eee1a-f367-11e6-80e0-3ee216178e57.png)

[UPDATE]
When setting a breakpoint in line 41 of NSScreen+Name.m i could print the description of "displayNames" variable to the console. The output seems correct but the UI won't show it.

![bildschirmfoto 2017-02-15 um 10 25 57](https://cloud.githubusercontent.com/assets/1955290/22968122/79f8d806-f369-11e6-8f0a-1154978c8202.png)

**Comment by domhardt** [comment]
I try to fix it. The problem seems to be the local language code. The if-statement contains "en_US" but my local language code is "de_DE"). I separated the or-combined if-statement and my assumption seems right.
![bildschirmfoto 2017-02-15 um 10 50 48](https://cloud.githubusercontent.com/assets/1955290/22968997/0e2d5116-f36d-11e6-9136-5251d07ef690.png)

**Comment by domhardt** [comment]
It seems that I found a solution. This code is a replacement for the lines [40](https://github.com/mpflanzer/splitshow/blob/master/SplitShow/NSScreen%2BName.m#L40)-[57](https://github.com/mpflanzer/splitshow/blob/master/SplitShow/NSScreen%2BName.m#L57):

`
       
    if (!displayNames)
    {
        CFRelease(displayInfo);
        return NSLocalizedString(@"Unknown", nil);
    }
    else
    {
        //TODO: 'en_US' ISN'T always available!
        NSString *localKey = [[(__bridge NSDictionary*)displayNames allKeys] firstObject];
    
       if (!CFDictionaryGetValueIfPresent(displayNames, (__bridge const void *)(localKey), (const void**)&displayName))
       {
           CFRelease(displayInfo);
           return NSLocalizedString(@"Unknown", nil);
       }
    

        if(displayName == NULL)
        {
            CFRelease(displayInfo);
            return NSLocalizedString(@"Unknown", nil);
        }
        else
        {
            NSString *_displayName = [NSString stringWithString:(__bridge NSString*)displayName];
            CFRelease(displayInfo);
            return _displayName;
        }
    }

`

Here is the result:
![bildschirmfoto 2017-02-15 um 12 19 05](https://cloud.githubusercontent.com/assets/1955290/22972207/fcdf740a-f378-11e6-9d1c-bbdf6f2dc910.png)

![bildschirmfoto 2017-02-15 um 12 20 11](https://cloud.githubusercontent.com/assets/1955290/22972251/211932e8-f379-11e6-9bf9-9af15b6ae9d6.png)

Can someone test it please?

**Comment by mpflanzer** [comment]
Thanks! I added a fix based on your suggestions. Could you please test if it is fixed for you in the latest version? https://github.com/mpflanzer/splitshow/releases/tag/v0.9.9-alpha

Please reopen if the issue still exists.
