### ISSUE TITLE
Doesn't work with Logitech Pointer M400

### ISSUE THREAD

**Issue by tcanvn** [mpflanzer/splitshow#58]
Logitech pointer (M400) doesn't work with this program.
I have ever used a older version of this program (splitshow.jar) and it works well with Logitech Pointer but the current version doesn't work.
Much appreciate if you can check this as this pointer is used very popular.
Thanks.

**Comment by mpflanzer** [comment]
I'm not aware that this program was ever available as JAR file. Where did you get that version?
What exactly doesn't work with the Logitech pointer? Will try do have a look what could be wrong. But as I don't have it it might be difficult to debug.

**Comment by tnull** [comment]
AFAIK the Logitech presenter inserts Page Up/Page Down instead of arrow keys. I know that this presenter used to work with SplitShow, too. However, newer versions do not seem to accept PgUp/PgDn as input, hence they do not work anymore.

**Comment by shuaiwang88** [comment]
0.9.8-alpha3 works with my Presenter R800 not the latest version.

**Comment by mpflanzer** [comment]
Thanks for pushing this issue back into my mind. I think I fixed it now. Could please confirm if the latest release (https://github.com/mpflanzer/splitshow/releases/tag/v0.9.9-alpha3) works for you?

**Comment by shuaiwang88** [comment]
it worked thank you!
